### ISSUE TITLE
Sample blows up on large files

### ISSUE THREAD

**Issue by hans-olav** [Microsoft/ProjFS-Managed-API#24]
I tried the "SimpleProvider" sample on some large files. It fails when a client app does a read at the beginning of a large file.

I haven't spent much time debugging, but in my repro, the client app opens a 34 GB file and does a 1 MB read at offset 0. ProjFS comes to the provider asking for range 0 - 2.2 GB. When the provider calls VirtualizationInstance::WriteFileData(), it returns 0x80070216 (ERROR_ARITHMETIC_OVERFLOW). From cursory inspection in the debugger, the arguments to the call seem reasonable (64K buffer).

It looks like the magic limit is unsigned int - just over 4 GB works fine.

**Repro:**

1. Create directory with a large file (I used some VHD I had sitting around):
```
D:\>dir "D:\Hyper-V\DokanWin10\Virtual Hard Disks"
 Volume in drive D is SSD
 Volume Serial Number is 6058-2621

 Directory of D:\Hyper-V\DokanWin10\Virtual Hard Disks

11/12/2018  02:44 PM    <DIR>          .
11/12/2018  02:44 PM    <DIR>          ..
11/12/2018  02:44 PM    36,712,742,912 DokanWin10.vhdx
               1 File(s) 36,712,742,912 bytes
               2 Dir(s)  265,872,031,744 bytes free
```

2. Project the directory using the sample:
`SimpleProviderManaged.exe --sourceroot D:\Hyper-V --virtroot D:\virt`

3. Do a read at the beginning of the file. For example:
```
using (FileStream fs = new FileStream(@"D:\virt\DokanWin10\Virtual Hard Disks\DokanWin10.vhdx", FileMode.Open, FileAccess.Read))
{
	byte[] buf = new byte[1024*1024];
	fs.Read(buf, 0, buf.Length);
}
```

**Comment by cgallred** [comment]
@hans-olav, what OS version are you running this on?

**Comment by hans-olav** [comment]
@cgallred: Windows 10 - 1809 (17763.437).

**Comment by cgallred** [comment]
1809 has a bug that prevents ProjFS from working properly on files > 4GB in size.  The bug was fixed in 19H1 (1903).  I'll look in to whether I can get the fix backported to 1809 (it requires a fix to Windows, since the error is not in the sample).
