### ISSUE TITLE
Determine "Who" performed an action. 

### ISSUE THREAD

**Issue by scottweedon** [microsoft/ProjFS-Managed-API#37]
Is it possible to have ProjFS return the username/SID of the user that deleted/created/updated a file? 

Our scenario see's ProjFS running in folder under a shared location. This works well, but without implementing a FileSystem watcher we cannot determine who did what. 

We can determine the creator of a new file by looking at the created file attributes, but im not aware that we can lookup who modified it.

**Comment by cgallred** [comment]
That would require platform support (this repo is for the managed API wrapper).  Could you please file an item in the Feedback Hub app?  Category: "Developer Platform", subcategory "Projected File System (ProjFS)".
