### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by edemartel** [microsoft/ProjFS-Managed-API#38]
Hello,

Currently, this library targets .NET Framework 4.6, and uses C++/CLI. I've heard that C++/CLI support will finally arrive with .NET Core 3.1. 

Are there any plans to target it? We plan to move to .NET Core as soon as possible.

Thanks!

**Comment by cgallred** [comment]
We are planning on supporting .NET Core.  I don't have a timeline I can share as of yet.

**Comment by cgallred** [comment]
.NET Core 3.1 support merged to master with #40

**Comment by cgallred** [comment]
@edemartel this has been uploaded to NuGet.org: https://www.nuget.org/packages/Microsoft.Windows.ProjFS/1.2.19351.1

**Comment by edemartel** [comment]
Christmas has come early this year! Thanks!
