### ISSUE TITLE
Handle 8.3 paths does not work

### ISSUE THREAD

**Issue by Debee416** [microsoft/ProjFS-Managed-API#45]
How to reproduce from console:
```
rem create file "VeryLongFileName.txt" in directory "C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data" 
echo blah>C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data\VeryLongFileName.txt
rem start projection
SimpleProviderManaged.exe --sourceroot C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data --virtroot C:\Test\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data
```

from another console:
`rmdir /s /q C:\Test\SomethingVeryLong`

expected result: directory "C:\Test\SomethingVeryLong" is removed
actual result: C:\Test\SomethingVeryLong\ANOTHE~1.10\data\VeryLongFileName.txt - The provider that supports file system virtualization is temporarily unavailable.

![image](https://user-images.githubusercontent.com/66071516/83145383-fddffa00-a0f4-11ea-9761-066bf8e4dd48.png)

**Comment by Debee416** [comment]
There is a hotfix: "fsutil.exe behavior set disable8dot3 1"

but out customer needs 8.3 paths due some legacy software :(

**Comment by cgallred** [comment]
I'm not able to reproduce this issue. What version of Windows is this?

**Comment by Debee416** [comment]
Please try "fsutil.exe behavior set disable8dot3 0" before creating directory C:\Test\
```
rmdir /s /q C:\Test
fsutil.exe behavior set disable8dot3 0
mkdir C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data
echo blah>C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data\VeryLongFileName.txt
SimpleProviderManaged.exe --sourceroot C:\Test\Source\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data --virtroot C:\Test\SomethingVeryLong\AnotherLongDirectoryName_1.0.0_Beta1.10\data
```

from another console:
`rmdir /s /q C:\Test\SomethingVeryLong`

![image](https://user-images.githubusercontent.com/66071516/87400035-9274bd80-c5b8-11ea-9dd8-a7d545e3888f.png)

![image](https://user-images.githubusercontent.com/66071516/87400061-9a346200-c5b8-11ea-8c10-0f6d3fbc793d.png)

![image](https://user-images.githubusercontent.com/66071516/87400117-b0422280-c5b8-11ea-9523-db51a92aa6d1.png)

**Comment by cgallred** [comment]
I did try the repro on a volume with short names enabled. This looks like a bug that is fixed in Windows build 18973 and above. Can you try to reproduce it on Windows 10 Version 2004 (i.e. May 2020 Update)? You could also try it on a recent [Insiders ](https://insider.windows.com) build.

**Comment by Debee416** [comment]
Ok, thanks. I will try on Version 2004. Right now there is some problem with Windows Update on my machine, probably caused by ProjFs.
0x80070171 can be googled as ERROR_FILE_SYSTEM_VIRTUALIZATION_UNAVAILABLE
![image](https://user-images.githubusercontent.com/66071516/87475268-c259aa80-c624-11ea-82b6-9dcc786ba622.png)

**Comment by cgallred** [comment]
Windows Update doesn't use ProjFS, so that error is certainly unexpected. The only way I can think of for that to happen is if somehow a virtualization root was created in a directory that Windows Update wants to use, and the provider for that virtualization root is no longer running. The system never does that, so something else would have to have done it.

In your experiments did you happen to set up a virtualization root in the %TEMP% directory or under some other directory that you didn't create yourself?

**Comment by Debee416** [comment]
Eh, that is embarrassing. I set c:\ as virtualization root by accident. 

Found it in Procmon, it shows "The provider that supports file system virtualization is temporarily unavailable" as Result 0xC000CE01.

![image](https://user-images.githubusercontent.com/66071516/87530365-88be8900-c690-11ea-81ee-cb7310989263.png)

Is there any way out of it?

**Comment by cgallred** [comment]
You should be able to fix it with `fsutil reparsePoint delete c:\` as Adminstrator.

**Comment by Debee416** [comment]
Nope :(
![image](https://user-images.githubusercontent.com/66071516/87585340-36f11f80-c6df-11ea-9a4c-f94e94fba0d4.png)

**Comment by cgallred** [comment]
Ah right, once again I'm thinking of more recent platform behavior. That approach should work starting with build 18876.

For your build, try unloading the ProjFS filter before doing it.  First make sure you have no running virtualization instances on the system, otherwise the first command below will hang until they're stopped. Then as Administrator:

1. `sc.exe stop prjflt`
1. `fsutil reparsePoint delete c:\`
1. `sc.exe start prjflt`

**Comment by Debee416** [comment]
Reparse point removed, May Update installed and rmdir with 8.3 paths is now working. Thanks a lot!
