### ISSUE TITLE
Question: How to enable the rename of directories with content?

### ISSUE THREAD

**Issue by miryamGSM** [microsoft/ProjFS-Managed-API#48]
We tried the rename operation for directories in the windows mirror file system.

- The rename of an empty directory works.
- But the rename of a directory with content fails with the following error:
`Error 0x80070032: The request is not supported`

Any help is welcome!

Thanks!

**Comment by cgallred** [comment]
Directory rename is not currently supported in ProjFS. It’s kind of complicated to get right and still have placeholder hydration (and other things) work properly beneath the renamed directory. We have an item on our backlog to consider supporting it in a future release of Windows.

Please file an item under "Suggest a feature" in Feedback Hub using the **Developer Platform** category, **Projected File System (ProjFS)** subcategory. That will help us track customer desire for the feature.
