### ISSUE TITLE
Any idea how a file might end up with a reparse tag of 0x0006008A?

### ISSUE THREAD

**Issue by FeralSquid** [microsoft/ProjFS-Managed-API#56]
Hello,

Several people are now using my solution that uses ProjFS successfully ... but so far I have one user that has ended up with a handful of their ProjFS files with a reparse tag of 0x0006008A ... that isn't one of the two ProjFS tags I know of (0x9000001C, 0xA0000022).

It doesn't have the Microsoft high bit set ... and it has non-zero values in its "reserved" range, so seems like it might even be bogus / an error?

My google searches haven't turned anything up yet that claims it... 

Any ideas?

**Comment by cgallred** [comment]
Sorry, doesn't look familiar to me. Like you guessed, that isn't a valid reparse tag:
```
//
// The following constant represents the bits that are valid to use in reparse tags.
//

#define IO_REPARSE_TAG_VALID_VALUES     (0xF000FFFF)

```
So the OS would reject it as a reparse tag since it falls afoul of `IO_REPARSE_TAG_VALID_VALUES`.
