### ISSUE TITLE
PreConvertToFull handler not notified

### ISSUE THREAD

**Issue by jkim0121** [microsoft/ProjFS-Managed-API#64]
I tried to hook up a handler to get PreConvertToFull notification. which is not a member of RequiredCallback. I traced it down to the source level and the code seems to handle the request correctly (registration). However, the .NET handler was not notified at all when I tried to hydrate. Could someone take a look at this? Thank you,

**Comment by cgallred** [comment]
That handler is not notified on hydration. That handler is notified when you modify a file under the virtualization root. See the documentation on [cache state in the virtualization root](https://docs.microsoft.com/en-us/windows/win32/projfs/cache-state). A "full" file is one whose primary data stream has been modified.
