### ISSUE TITLE
Document C++ runtime as prerequisite

### ISSUE THREAD

**Issue by hakito** [microsoft/ProjFS-Managed-API#66]
On a non-development machine the loading of ProjectedFSLib.Managed.dll fails with a FileNotFoundException if C++ runtime  (https://aka.ms/vs/16/release/vc_redist.x64.exe) is not installed.

**Comment by cgallred** [comment]
That is a common requirement for the majority of C++ applications or libraries developed with Visual Studio. The requirements for deploying a native desktop application built by Visual C++ are documented [here](https://docs.microsoft.com/en-us/cpp/windows/deploying-native-desktop-applications-visual-cpp).

**Comment by hakito** [comment]
Yes, if I compile the project on my own - that makes sense. But when simply consuming the nuget package, it is not so obvious.

**Comment by cgallred** [comment]
I'll add a note to the README to clarify that even if using the pre-compiled library you have to install the redistributable.
