### ISSUE TITLE
DirectoryEnumerationResults.Add symlink override is incompatible with EnumerateFileSystemInfos on .NET Framework

### ISSUE THREAD

**Issue by yerudako** [microsoft/ProjFS-Managed-API#81]
**Context**: 
Symlink support is being added in #73. The DirectoryEnumerationResults.Add method calls **PrjFillDirEntryBuffer2** native API method. For certain environment/symlink combinations, such as ones [in these tests](https://dev.azure.com/projfs/ci/_build/results?buildId=183&view=logs&j=cfa20e98-6997-523c-4233-f0a7302c929f&t=fee8e8c4-1226-5b39-c674-4b5c0e0c3987), PrjFillDirEntryBuffer2 returns ERROR_INSUFFICIENT_BUFFER for the first enumeration element.

It is [expected](https://docs.microsoft.com/en-us/windows/win32/api/projectedfslib/nf-projectedfslib-prjfilldirentrybuffer2) of the provider to return ERROR_INSUFFICIENT_BUFFER as a callback result if the error happened on the first enumeration element. SimpleManagedProvider is an example of a provider doing this according to the guidelines.

**Issue**: 
ERROR_INSUFFICIENT_BUFFER result coming from an enumeration callback is handled correctly in .NET Core, but not .NET Framework.

•	Framework is using FindFirstFile()/FindNextFile(). There is no handling in the enumerator for buffer size results, in fact those functions’ doc pages do not discuss INSUFFICIENT_BUFFER as a possible result.
•	NetCore is using NtQueryDirectoryFile() and related APIs, using resizing buffers.

.NET Framework:
[directoryinfo.cs (microsoft.com)](https://referencesource.microsoft.com/#mscorlib/system/io/directoryinfo.cs,d215b374681bf5ab)
[filesystemenumerable.cs (microsoft.com)](https://referencesource.microsoft.com/#mscorlib/system/io/filesystemenumerable.cs,193)
.NET Core:
[FileSystemEnumerator.Windows: runtime/FileSystemEnumerator.Windows.cs· dotnet/runtime (github.com)](https://github.com/dotnet/runtime/blob/09c1a1f7b0c477890b04912d8dd4f742f80faffc/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs)
[FILE_FULL_DIR_INFORMATION derived from calling ntdll.dll : runtime/Interop.FILE_FULL_DIR_INFORMATION.cs dotnet/runtime (github.com)](https://github.com/dotnet/runtime/blob/09c1a1f7b0c477890b04912d8dd4f742f80faffc/src/libraries/Common/src/Interop/Windows/NtDll/Interop.FILE_FULL_DIR_INFORMATION.cs#L62)

**Workaround**: 
.NET Framework 4.8 clients should not use the Add override with the symlink target. 
If the symlink support is needed, .NET Core runtime could be used instead.

**Comment by cgallred** [comment]
This turned out to be a bug in the sample SimpleProvider application provoked by different behavior between .NET Framework and .NET Core. Clients of either version can use the Add override with the symlink target.
